### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dineshr93** [dmarko484/mastering-live-view-development-in-golang#1]
Hi,  I am taking your course in udemy "mastering-liveview-development-in-go-golang" 

I get below error while accessing the server http://localhost:8080/thermostat

i am still in section 4 (no nats library is used) but here it is there.

```

\mastering-live-view-development-in-golang> go run .
2023/10/13 10:00:53 Application is starting ...
2023/10/13 10:01:07 Mounting application
2023/10/13 10:01:07 http: panic serving [::1]:51924: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1()
        D:/go/src/net/http/server.go:1868 +0xb9
panic({0x6d9fe0?, 0xac0700?})
        D:/go/src/runtime/panic.go:920 +0x270
github.com/nats-io/nats%2ego.(*EncodedConn).subscribe(0x0, {0x74b5a4, 0x7}, {0x0, 0x0}, {0x6b60a0, 0xc0000322a0})
        D:/go/pkg/mod/github.com/nats-io/nats.go@v1.22.1/enc.go:237 +0x1d1
github.com/nats-io/nats%2ego.(*EncodedConn).Subscribe(...)
        D:/go/pkg/mod/github.com/nats-io/nats.go@v1.22.1/enc.go:174
main.thermoMount({0x801620?, 0xc0000321b0}, {0x804b48?, 0xc000070010})
        C:/Users/dira271641/dev/golang/mastering-live-view-development-in-golang/main.go:49 +0x14d
github.com/jfyne/live.(*HttpEngine).get(0xc0001a89c0, {0x801620, 0xc0000321b0}, {0x800cb0, 0xc0000a4000?}, 0xc000088000)
        D:/go/pkg/mod/github.com/jfyne/live@v0.15.3/http.go:242 +0x4bd
github.com/jfyne/live.(*HttpEngine).ServeHTTP(0xc0001a89c0, {0x800cb0, 0xc0000a4000}, 0xc000088000)
        D:/go/pkg/mod/github.com/jfyne/live@v0.15.3/http.go:93 +0x14a
net/http.(*ServeMux).ServeHTTP(0xb2a1a0?, {0x800cb0, 0xc0000a4000}, 0xc000088000)
        D:/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc000032060?}, {0x800cb0?, 0xc0000a4000?}, 0x6?)
        D:/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0002862d0, {0x801620, 0xc000185bf0})
        D:/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
        D:/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by dmarko484** [comment]
Hi, I'm looking into the traceback and can see: 
D:/go/src/runtime/panic.go:920 +0x270
[github.com/nats-io/nats%2ego.(*EncodedConn).subscribe(0x0](http://github.com/nats-io/nats.go.(*EncodedConn).subscribe(0x0), {0x74b5a4, 0x7}, {0x0, 0x0}, {0x6b60a0, 0xc0000322a0})

... do you run NATS server (https://github.com/nats-io/nats-server), as connection is required ?

**Comment by dineshr93** [comment]
> ... do you run NATS server (https://github.com/nats-io/nats-server), as connection is required ?

Okay I downloaded the server from https://github.com/nats-io/nats-server/releases/tag/v2.10.3
and started the server (nats-server.exe -js).  now it is working

**Comment by dmarko484** [comment]
Thanks for letting me know ...
